# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "e5e482d225d229108b2294ec789657cb2cf34a52fadabdd2fa1e6507f6422daf"  # generated for local testing
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
redis:
  url: redis://redis:6379/0

search:
  formats:
    - html
    - json # 这一行至关重要！

engines:
  - name: wikidata
    engine: wikidata
    disabled: true  # 添加这一行来禁用wikidata引擎
  # ... 其他引擎配置
