# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: false
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "e5e482d225d229108b2294ec789657cb2cf34a52fadabdd2fa1e6507f6422daf"  # generated for local testing
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
redis:
  # redis.url is deprecated; use valkey.url instead. Keep here for reference if needed.
  # url: redis://redis:6379/0

valkey:
  url: redis://redis:6379/0

search:
  formats:
    - html
    - json # 这一行至关重要！

engines: []

# Explicit per-engine configuration to ensure engines are disabled when not configured
engines_config:
  ahmia:
    disabled: true
  torch:
    disabled: true
  "yacy images":
    disabled: true
  wikidata:
    disabled: true

# engines_blocklist 会显式阻止这些引擎被加载
engines_blocklist:
  - wikidata
  - ahmia
  - torch
  - "yacy images"
